#!/bin/bash
(
 cd buildroot-2021.02
 ./output/host/bin/qemu-system-aarch64 \
 -M virt -cpu cortex-a53 -nographic -smp 1 \
 -m 1024M \
 -kernel output/images/Image -append "rootwait root=/dev/vda console=ttyAMA0" \
 -netdev user,id=eth0,hostfwd=tcp::8888-:8810,hostfwd=tcp::2222-:22\
 -device virtio-net-device,netdev=eth0 \
 -drive file=output/images/rootfs.ext2,if=none,format=raw,id=hd0 \
 -device virtio-blk-device,drive=hd0 \
 -device virtio-rng \
 -audiodev driver=pa,id=snd0 \
 -device intel-hda -device hda-duplex,audiodev=snd0
)

